---
title: "Lab11.Rmd"
author: "Elisena"
date: "12/23/2021"
---


```{r, fig.width=2.7,fig.height=2.7}
ps <- rnorm(100,-1,2)
s<-1:100
plot_df<-data.frame(s,ps)
ggplot(plot_df, aes(x=ps))+
  geom_histogram(fill="green",
                 color="black")+
  coord_cartesian(xlim=c(-4,4))+
   theme_classic(base_size=8)+
  xlab("Log Likelihood Ratio")+
  coord_cartesian(ylim=c(10,40))+
  ylab("Participants (in Each condition)")+
  ggtitle("Women Performed Surgery")+
  geom_vline(xintercept=0,linetype=2)
#I tried to doing this a different way but I end up being confeused
```



```{r, fig.width=4,fig.height=5}
Gender <- rep(c("Men Performed Surgery \n n = 152",
            "Women Performed Surgery \n n = 142"), each =3)
Parameter <- rep(c("Prior",
               "Model \n Posterior",
               "Reported \n Posterior"), 2)
p <- c(.7, .88, .87, .29, .72, .76)
ci <- c(.05, .05, .05, .05, .05, .05)
plot_df <- data.frame(p, ci, Gender, Parameter)
plot_df$Parameter <- factor(plot_df$Parameter, 
                         levels = c("Prior",
               "Model \n Posterior",
               "Reported \n Posterior"))
ggplot(plot_df, aes(x=Parameter, y=p, fill=Parameter))+
  geom_bar(stat="identity", position="dodge")+
  facet_wrap(~Gender)+
  theme_classic(base_size=11)+
  scale_fill_manual(values=c("#6daaf8", "#f86daa", "#bb8dbc"))+
  ylab("P(Target = Doctor)")+
  scale_y_continuous(breaks=seq(0,1,.1),labels = scales::percent)+
  coord_cartesian(ylim=c(0,1))+
  theme(panel.grid = element_blank(),
        panel.spacing.x = unit(0,"line"),
        panel.border = element_blank(),
        panel.background = element_blank())+
  theme(strip.background = element_rect(colour = 'white', fill = 'white', size = 0))+
  theme(legend.position = "none")
```



```{r}
a <- c(1,2,3,2,3,4,5,4)
b <- c(4,3,4,3,2,1,2,3)
plot_df <- data.frame(a,b)

# basic scatterplot
ggplot(plot_df, aes(x=a,y=b))+
  geom_point()
```