---
title: "Lab3.Rmd"
author: "Elisena"
date: "9/25/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)

```


```{r}
observations <- rnorm(5*25,mean=200, sd=100)
samples <- rep(1:5,each =25)
my_data <- data.frame(samples,observations)

library(dplyr)

means <- my_data %>%
  group_by(samples) %>%
  summarize(sample_mean = mean(observations))

library(ggplot2)

ggplot(means, aes(x = samples, y =sample_mean))+
  geom_bar(stat="identity")
#0
```



```{r}
observations <- rnorm(5*25,mean=200, sd=100)
samples <- rep(1:5,each =25)
my_data <- data.frame(samples,observations)

means <- my_data %>%
  group_by(samples) %>%
  summarize(sample_mean = mean(observations),
            sample_sd = sd(observations))

ggplot(means, aes(x = samples, y =sample_mean))+
  geom_bar(stat="identity") +
  geom_errorbar(aes(ymin = sample_mean - sample_sd,
                    ymax = sample_mean + sample_sd),
                width = .25)
#0
```


```{r}

observations <- rnorm(2*10000,mean=10, sd=5)
samples <- rep(1:10000,each =2)
my_data <- data.frame(samples,observations)

summarized_data <- my_data %>%
  group_by(samples) %>%
  summarize(sample_means = mean(observations))

mean(summarized_data$sample_means)

##

observations <- rnorm(5*10000,mean=10, sd=5)
samples <- rep(1:10000,each =5)
my_data <- data.frame(samples,observations)

summarized_data <- my_data %>%
  group_by(samples) %>%
  summarize(sample_means = mean(observations))

mean(summarized_data$sample_means)

#####

sample_sizes <- c(2,5,10,50,100)
sim_sample_means <- c()
for(i in 1: length(sample_sizes)){
  observations <- rnorm(sample_sizes [i]*10000,mean=10, sd=5)
  samples <- rep(1:10000,each = sample_sizes[i])
  my_data <- data.frame(samples,observations)
  
  summarized_data <- my_data %>%
    group_by(samples) %>%
    summarize(sample_means = mean(observations))

  sim_sample_means[i] <- mean(summarized_data$sample_means)
}

sim_data <- data.frame(sample_sizes, sim_sample_means)

ggplot(sim_data, aes(x=sample_sizes, y=sim_sample_means, group=1))+
  geom_point()+
  geom_line()
  coord_cartesian(ylim = c(0,20) )
  #0
```


```{r}

sd_N <- function(x){
  sqrt(sum((mean(x)-x)^2) / length(x))
}
#####
sample_sizes <- c(2,5,10,50,100)
sim_sample_sd <- c()
sim_sample_sd_N <- c()
for(i in 1: length(sample_sizes)){
  observations <- rnorm(sample_sizes [i]*10000,mean=10, sd=5)
  samples <- rep(1:10000,each = sample_sizes[i])
  my_data <- data.frame(samples,observations)
  
  summarized_data <- my_data %>%
    group_by(samples) %>%
    summarize(sample_sd = sd(observations),
              sample_sd_N = sd_N(observations))

  sim_sample_sd[i] <- mean(summarized_data$sample_sd)
  sim_sample_sd_N[i] <- mean(summarized_data$sample_sd_N)
}

sim_data <- data.frame(n = rep(sample_sizes,2),
                       est = c(sim_sample_sd_N,sim_sample_sd),
                       formula = c(rep("N",5), rep("N-1",5)))

ggplot(sim_data, aes(x=n, y=est, group=formula, color = formula))+
  geom_point()+
  geom_line()+
  coord_cartesian(ylim = c(0,10) )

#0
```