---
title: "Lab5.Rmd"
author: "Elisena"
date: "10/13/2021"
---

```{r}

pnorm(2.5, mean = 0, sd =1, lower.tail = FALSE)

my_sample <- rnorm(1000000, mean =0, sd =1)

selection <- my_sample[my_sample > 2.5]
length(selection)/1000000

```



```{r}

pnorm(q=130, mean =100, sd =10, lower.tail = FALSE)

10000*pnorm(q=130, mean =100, sd =10, lower.tail = FALSE)

some_observations <- rnorm(10000, mean =100, sd =10)

length(some_observations[some_observations > 130])/10000

```



```{r}

sampling_distribution <- replicate(10000, mean(rnorm(25, mean =10, sd =20)))

hist(sampling_distribution)

length(sampling_distribution[sampling_distribution>= 12])/10000


```


```{r} 

sampling_distribution <- replicate(10000, mean(rnorm(100, mean =10, sd =20)))

hist(sampling_distribution)

length(sampling_distribution[sampling_distribution>= 12])/10000
#yes it is different, because the numbers were randomly picked and the samples are not equivalent 
```


```{r}

sampling_distribution <- replicate(10000, sd(rnorm(25, mean =10, sd =20)))

hist(sampling_distribution)

length(sampling_distribution[sampling_distribution <= 15])/10000

```