---
title: "Lab6.Rmd"
author: "Elisena"
date: "10/19/2021"
---

```{r}

group_one <- c(3,4,5,6,7)
group_two <- c(5,3,2,4,6)

randomization_test <-function(A,B, resamples = 100){
  group_A_mean <- mean(A)
  group_B_mean <- mean(B)
  mean_difference <- group_A_mean - group_B_mean
  
  all_means <- c(A,B)
  
  possible_differences <- c()
  for(i in 1:resamples){
    resample <- sample(all_means)
    new_A_mean <- mean(resample[1:length(A)])
    new_B_mean <- mean(resample[(length(A)+1):length(all_means)])
    possible_differences[i] <- new_A_mean-new_B_mean
  }
  
  the_plot <- ggplot2::qplot(possible_differences)+
    ggplot2::geom_histogram(color="orange")+
    ggplot2::geom_vline(xintercept = mean_difference, color="red")+
    ggplot2::theme_classic()
  
  p_value <- length(possible_differences[possible_differences >= mean_difference])/resamples
  
  test_output <- list(A_mean = group_A_mean,
                      B_mean = group_B_mean,
                      difference = mean_difference,
                      randomization = possible_differences,
                      plot = the_plot,
                      p_value = p_value)
  
  return(test_output)
  
}

randomization_test(A=group_one,
                   B=group_two,
                   resamples=1000)

# for group A, i would say that the order numbers are going up by one step while group B the numbers are not in order. when adding the numbers an dividing the by the amount that's in the set, their means are different. the mean of A is equal to 5 while B is equal to 4. 

```



```{r}

the_data <- read.csv("open_data/SchroederEpley2015data.csv", header = TRUE)

library(dplyr)

group_0 <- the_data %>%
  filter(CONDITION == 0) %>%
  select(Intellect_Rating)

group_0 <- group_0$Intellect_Rating
  
group_1 <- the_data %>%
  filter(CONDITION == 1) %>%
  select(Intellect_Rating)
  
group_1 <- group_1$Intellect_Rating
  

randomization_test(A=group_0,
                   B=group_1,
                   resamples=1000)

```