---
title: "Lab9.Rmd"
author: "Elisena"
date: "10/19/2021"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
```



```{r}

the_data <- read.csv(file="When not choosing leads to not liking_Data (2).xlsx")

library(dplyr)
e1_data <- the_data %>%
  filter(ExperimentNumber == "1")

sum_C <- sum(e1_data$Infant.Chose.C)
total_C <- length(e1_data$Infant.Chose.C)
(binomial_p <- pbinom(q = total_C - sum_C,
                      size = total_C, 
                      prob = .5, 
                      lower.tail = TRUE)*2)
#gender
library(tidyr)
gender_choice_table <- e1_data %>%
  group_by(Gender, Infant.Chose.C) %>%
  summarize(counts = n()) %>%
  pivot_wider(names_from = c(Gender),
              values_from = counts)
gender_choice_table <- gender_choice_table[,2:3]
(gender_Xsq <- chisq.test(gender_choice_table))  
uncorrected_Xsq <- sum((gender_Xsq$observed-gender_Xsq$expected)^2/gender_Xsq$expected)
gender_Xsq_unc <- pchisq(uncorrected_Xsq,1,lower.tail = FALSE)

#age
age_table <- e1_data %>%
  group_by(AgeMonths, Infant.Chose.C) %>%
  summarize(counts = n()) %>%
  pivot_wider(names_from = c(AgeMonths),
              values_from = counts)
age_table[is.na(age_table)] <- 0
age_table <- as.matrix(age_table[,2:21])
(age_xs <- chisq.test(age_table))
```
